name: Generate Snake animation
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Snake animation
      uses: Platane/snk@master
      with:
        github_user_name: kwonggary
        svg_out_path: ./github-contribution-grid-snake.svg
